import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";
import { SignIn, SignInButton, useUser } from "@clerk/nextjs";
import { type Post } from "@prisma/client";
import CreatePostWidget from "@/components/CreatePostWidget";
import { type PostAuthor } from "@/utils";
import PostView, { PostViewProps } from "@/components/PostView";

const Home: NextPage = () => {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();
  console.log("Data >>>", data); // <<--*

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Error Loading Data. Try Again.</div>;

  return (
    <>
      <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreatePostWidget />}
          </div>
          <div className="flex flex-col">
            {data.map(({ post, author }: PostViewProps) => (
              <PostView key={post.id} post={post} author={author} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
